<?php
return [
	"description" => "Ferry Líneas Romero is a family-owned company that offers ferry trips and excursions in Lanzarote, Fuerteventura, and La Graciosa. Learn about our story.",
	"future_description" => "The Romero siblings grew up on La Graciosa and are deeply in love with their land, its wild landscape, and the scent of the sea. That is why they are fully aware of the importance of protecting the island and show the utmost respect for its surroundings and nature. In this way, Líneas Romero meticulously complies with environmental regulations and is a company that promotes sustainable tourism. Líneas Romero currently operates a regular maritime service between the islands of Fuerteventura, Lanzarote, and La Graciosa. <br><br> In addition, it offers excursions and unique tourist experiences, such as sailing catamaran trips to explore the islands and enjoy various water activities. It also provides a Waterbus service, which is the most convenient way to travel between Puerto Calero and Puerto del Carmen (Lanzarote). At Líneas Romero, they are firmly committed to innovation; constantly reinventing themselves and offering new services to meet users’ needs. Likewise, they regularly renew their fleet, incorporating faster, more modern vessels equipped with the latest technology.",
	"future_title" => "FUTURE",
	"heading" => "ABOUT US",
	"heading_subtitle" => "90 years of dedicated island connections",
	"history_description" => "It all began when Jorge M. Toledo founded Líneas Romero, becoming the first maritime postal company to connect La Graciosa and Lanzarote. In its early days, it operated with a simple rowing boat that transported mail between these two beautiful Atlantic islands. This postal vessel was later inherited by Jorge M. Toledo’s daughter, Juana González Toledo, who would later marry Juan Romero. <br><br> It was in 1970 when Juan Romero took over the company, thereby expanding its services. Juan ran Líneas Romero until 1985, when the business was inherited by their four children: Luis, Juan Jorge, Federico, and Rosa Romero, who currently manage the company. The Romero family still lives on La Graciosa and, although their business has continued to grow, their values remain unchanged. They love their work and their island above all else; and their passion has led them on a path full of success.",
	"history_title" => "HISTORY",
	"keywords" => "líneas romero history federico romero",
	"section_description" => "Tradition and innovation are the two main hallmarks of Líneas Romero. A family-owned company dedicated to the maritime sector, connecting the easternmost Canary Islands since 1930.",
	"section_title" => "DISCOVER THE HISTORY OF LÍNEAS ROMERO",
	"title" => "Líneas Romero Timetables. Travel with Líneas Romero in the fastest and most comfortable way.",
];