<?php
return [
	"access_declaration" => "To access our services, you declare that you are <b>of legal age</b> and have sufficient legal capacity to use our services, according to your national law. Access and navigation on the website, or the use of its services, implies the express and full acceptance of each and every one of these General Terms and Conditions, including the Specific Conditions set for certain promotions, as well as the Privacy and Cookies Policies, in accordance with the current regulations on Personal Data Protection. Please, we recommend that you read them carefully to understand what type of data is collected through our website, for what purposes, and what rights you have in relation to it.",
	"description" => "Ferry Líneas Romero is a family-owned company that offers ferry trips and excursions in Lanzarote, Fuerteventura, and La Graciosa. Learn about our story.",
	"heading" => "ABOUT US",
	"intro" => "This website uses cookies and similar technologies to provide the service, as well as to allow us to improve it by collecting statistics on its use and for other purposes.",
	"keywords" => "líneas romero history federico romero

",
	"section_1_content" => "In compliance with Law 34/2002, of July 11, on Information Society Services and Electronic Commerce, the identifying details of the owner of the Website Portal are: <br> <br>
LINEAS ROMERO, S.L. <br>
Avda. Virgen del Mar, nº119, La Graciosa, 35540, Lanzarote <br> <br>
Registration details: Registered in the Mercantile Registry of Arrecife, volume 4, page 193, section 8, sheet IL-182 and registration 2. <br> <br>
For any questions or inquiries, you can contact us via phone: 928842085 or email: info@lineasromero.com <br> <br>
Access to the website implies the User's express acceptance of these General Terms and Conditions of Use, which may be modified in whole or in part, or replaced by others, by the owner at any time without prior notice. We recommend that you review these terms from time to time to check for any modifications, which will be published in the same section.",
	"section_1_title" => "1.- Legal Information.",
	"section_2_content_1" => "The following General Terms and Conditions govern the use and access to the website portal, with the aim of establishing guidelines for its proper use and conduct. LINEAS ROMERO, S.L. provides users with information about the use, services, and content hosted on the website. Through this, the User has access to information on specific products and services, tools, and applications.",
	"section_2_content_2" => "The data and information about products or services, prices, features, or other relevant details provided through the website are created, provided, and updated by suppliers and third-party companies. LINEAS ROMERO, S.L. is in no case responsible for this data and information nor assumes any obligation regarding them.",
	"section_2_content_3" => "The User agrees to make proper use of the content, services, applications, and tools that are accessible, in accordance with the law and these General Terms of Use, and, where applicable, with the Specific Conditions that may be established for access to certain services and applications, while respecting other Users at all times.",
	"section_2_content_4" => "In the event of total and/or partial non-compliance by the User with these General Terms of Use, LINEAS ROMERO, S.L. reserves the right to deny access to the website, without prior notice to the User.",
	"section_2_title" => "2.- General Terms of Use.",
	"section_3_conclusion" => "The User will be responsible for all damages and losses of any kind that LINEAS ROMERO, S.L. or any third party may suffer as a result of breaching any of the obligations they are subject to under these \"General Terms of Use\" or the law in relation to accessing and/or using the website.",
	"section_3_intro" => "By accepting these General Terms of Use, the User expressly agrees",
	"section_3_item_1" => "Do not take any action intended to harm, block, damage, disable, overload, temporarily or permanently, the functionalities, tools, content, and/or infrastructure of the website, in a way that prevents its normal use.",
	"section_3_item_2" => "Guard and maintain the confidentiality of the access keys associated with your username, being responsible for the use of these personal and non-transferable access keys by third parties.",
	"section_3_item_3" => "Do not introduce or create defamatory or slanderous content, either about other users or third-party companies unrelated to LINEAS ROMERO, S.L.
",
	"section_3_item_4" => "Do not use any of the materials and information contained on this website for illegal purposes and/or those expressly prohibited in these General Terms of Use, as well as the specific conditions that may be established for certain applications and/or utilities, and that are contrary to the rights and interests of LINEAS ROMERO, S.L., its users, and/or third parties.",
	"section_3_item_5" => "Do not offer or distribute products and services, nor carry out unsolicited advertising or commercial communications to other users and visitors of LINEAS ROMERO, S.L.",
	"section_3_title" => "3.- General Obligations of the User.",
	"section_4_content_1" => "The website, the pages it comprises, and the information or elements contained within them (including texts, documents, photographs, drawings, graphic representations, for which it holds ownership or which are owned by third parties who authorise the owner to use them, among others), as well as logos, trademarks, trade names, or other distinguishing signs, are protected by intellectual and/or industrial property rights, of which LINEAS ROMERO, S.L. is the owner or holds authorisation for their use and public communication from the legitimate owners.",
	"section_4_content_2" => "The User agrees to use the content diligently and correctly, in accordance with the law, morals, and public order. LINEAS ROMERO, S.L. authorises the User to view the information contained on this website, as well as to make private reproductions (simple downloading and storage on their computer systems), provided that the elements are solely intended for personal use. In no case shall this be considered an authorisation or licence over the property rights of LINEAS ROMERO, S.L. or the legitimate owners of the rights.",
	"section_4_content_3" => "The User is not authorised to distribute, modify, assign, or publicly communicate the information contained on this website in any form and for any purpose.",
	"section_4_title" => "4.- Intellectual and Industrial Property.",
	"section_5_content_1" => "Connections and links to third-party websites or pages have been established solely as a convenience for the User. LINEAS ROMERO, S.L. is in no case responsible for them or their content.",
	"section_5_content_2" => "LINEAS ROMERO, S.L. assumes no responsibility for the existence of links between the contents of this site and content located outside of it or any other mention of external content. Such links or mentions are solely for informational purposes and, in no case, imply endorsement, approval, marketing, or any relationship between LINEAS ROMERO, S.L. and the individuals or entities responsible for or managing such content or the owners of the websites where they are found.",
	"section_5_content_3" => "To create links to the website, explicit written permission from the owners of the portal is required.",
	"section_5_title" => "5.- Links.",
	"section_6_conclusion" => "LINEAS ROMERO, S.L. is not responsible, nor will it be held liable to users or third parties for the actions of any third party unrelated to LINEAS ROMERO, S.L. that may lead to or involve unfair competition, unlawful advertising, or the infringement of intellectual and industrial property rights, trade secrets, contractual commitments of any kind, rights to honour, personal and family privacy, image rights, property rights, or any other rights belonging to a third party due to the transmission, dissemination, storage, provision, reception, acquisition, or access to the content.",
	"section_6_content_1" => "LINEAS ROMERO, S.L. assumes no responsibility for damages, losses, claims, or expenses caused by:",
	"section_6_intro" => "LINEAS ROMERO, S.L. does not guarantee continuous access, nor the proper viewing, downloading, or usefulness of the elements and information contained on the portal's pages, which may be impeded, hindered, or interrupted by factors or circumstances beyond its control or outside its will, nor by those caused by the presence of computer viruses on the Internet.",
	"section_6_item_1" => "Interferences, interruptions, failures, omissions, delays, blockages, or disconnections caused by errors in telecommunication lines and networks or by any other reason beyond the control of LINEAS ROMERO, S.L.",
	"section_6_item_2" => "Illegitimate intrusions through the use of malicious programs of any kind and through any communication means, such as computer viruses or any other.",
	"section_6_item_3" => "Improper or inappropriate use of the LINEAS ROMERO, S.L. website.",
	"section_6_item_4" => "Security or navigation errors caused by a malfunction of the browser or the use of outdated versions.",
	"section_6_title" => "6.- Liability.",
	"section_7_content" => "The entire personal data processing policy can be found in the Privacy Policy, which is an integral part of these General Terms and Conditions, but for simplicity, we have placed it in a separate document: Privacy Policy.",
	"section_7_title" => "7.- Protection of Personal Data.",
	"section_8_content_1" => "This Legal Notice and its terms and conditions will be governed by and interpreted in accordance with Spanish Legislation. The user, by simply accessing the website or obtaining the status of a registered user, irrevocably gives their consent for the competent courts by default to hear any legal action arising from or related to these terms, or their use of this site or browsing carried out on it.",
	"section_8_content_2" => "If any clause or section of these General Terms and Conditions, which is not essential to its existence, is declared null or unenforceable, the validity of the remaining clauses will not be affected.",
	"section_8_title" => "8.- Legislation.",
];