<?php
return [
	"description" => "Ferry Líneas Romero is a family-owned company that offers ferry trips and excursions in Lanzarote, Fuerteventura, and La Graciosa. Learn about our story.",
	"heading-text" => "EXPLORE THE OLDEST ISLAND <br> OF THE CANARIES",
	"keywords" => "líneas romero history federico romero",
	"text-1" => "If there is one island in the Canary Archipelago that rivals the Caribbean, it's Fuerteventura. Its golden sandy beaches and emerald waters captivate everyone who arrives. With Líneas Romero, you can travel to Fuerteventura from Lanzarote on our fast ferry, which takes only 30 minutes. Want to know everything that awaits you on this wonderful island? Don't miss its history, beaches, and the best hidden corners of Fuerteventura.",
	"text-10" => "In just half an hour by boat, you can discover this magnificent spot. Lobos Island has two beaches: La Concha, with views of the Corralejo dunes, is a peaceful bay that is protected from the waves. On the other side, there is the Puertito de Lobos, where the contrast between the emerald green of the water, the dark volcanic rock, and the beige color of the dock's wooden structure will captivate you.",
	"text-11" => "If you’re someone who enjoys getting off the beaten path, in Fuerteventura you’ll find some hidden spots that are truly breathtaking.",
	"text-12" => "Hiking enthusiasts can find the ideal place to enjoy the unique geography of Fuerteventura in the Barranco de Las Peñitas and Barranco de Los Enamorados. <br><br> The Barranco de Las Peñitas is located near the village of Betancuria. It features a trail of just over two kilometers, where the Ermita de la Virgen de La Peña, a peculiar religious building integrated into the stone of the ravine, is also located. <br><br> On the other hand, the Barranco de Los Enamorados, located in the municipality of La Oliva—south of the village of Lajares—is the closest thing to the Antelope Canyon in the United States that can be found in the Canary Islands. It is a unique space formed by fossilised dunes shaped by water.",
	"text-13" => "For those who prefer the beach, Esquinzo is one of the most tranquil and unique spots in Fuerteventura, frequented by some surfers. The beach can be accessed either by walking through the ravine of the same name, which originates from the Tindaya mountain, or from El Cotillo.",
	"text-14" => "Fuerteventura is home to a rich, unique, and distinctive fauna and flora. It is inhabited by many species of birds, some endemic to the Canary Islands and others migratory, which cross its sky and rest on the island during their long journeys.

<br><br> Regarding its vegetation, its arid appearance hides a rich variety of unique species adapted to the climatic conditions. Notable are the vast palm groves, which form lush oases that seem straight out of a movie.

<br><br> It has no forests and is dominated by plains, volcanic cones, mountains, ravines, and experiences great environmental aridity. Because of this, the farmers of Fuerteventura have been forced to sharpen their ingenuity, adapting to the harsh environment and efficiently utilizing both the scarce rainfall and the frequent winds. The landscape has been modified by human presence, achieving a unique harmony in the world.

<br><br> Visiting the island, enjoying its landscape and people, is easy with Líneas Romero. Travel on our ferries from Playa Blanca in Lanzarote to Corralejo, one of the most important tourist centers in Fuerteventura. In just half an hour, you can reach this stunning island!

<br><br> Additionally, with Líneas Romero, you also have the option to book excursions from Fuerteventura to the island of Lanzarote, where you can enjoy true volcanic landscapes and visit tourist hotspots such as the Timanfaya National Park. Escape with the best company, breathe in the Atlantic breeze, and live new experiences.",
	"text-2" => "Fuerteventura is a unique and captivating island that leaves no one indifferent. It is the closest Canary Island to Africa and the second largest, after Tenerife, with an area of 1,659 km² and 150 kilometers of beaches washed by the Atlantic Ocean. Its beauty is protected; it is a territory designated as a Biosphere Reserve and Starlight Reserve by UNESCO. If you want to discover it, Líneas Romero offers a regular ferry service that connects Lanzarote and Fuerteventura in just half an hour. <br><br> The island enjoys a dream climate, with more than 300 days of sunshine a year and exceptionally low rainfall. Fuerteventura's climate is arid, with areas that belong to both desert and subtropical arid climates. Furthermore, the wind and wave conditions make it perfect for sports enthusiasts such as surfing, windsurfing, and kitesurfing. <br><br> Without a doubt, it is a desert jewel, but with miles of paradisiacal beaches with white or golden sand and turquoise waters that enchant everyone who visits.",
	"text-3" => "The origin of Fuerteventura is estimated to be around 1,000 BC, with the arrival of the \"majos,\" the first people to settle on the island, who were engaged in agriculture, livestock farming, and fishing. The name comes from the Guanche term \"majo,\" which meant \"rustic footwear.\" <br><br> The island's name has changed over time. During the period of the \"majos\" arrival, it was known as Herbania, with the territory divided into two kingdoms: Maxorata to the north and Jandía to the south. During the Roman occupation, it was called Planaria due to the island's flat geography, and Capraria, due to the large number of goats that inhabited the area. <br><br> It was in 1402 when Jean Bethencourt and Gadifer de la Salle began their expeditions to Fuerteventura. It wasn’t until 1405 that the territory became part of the Kingdom of Castile. Subsequently, attacks by barbarians and pirates became a regular occurrence on the island.",
	"text-4" => "From a geological perspective, it is the oldest island in the Canary Islands, formed millions of years ago. Today, it has a gentle relief due to erosion, although recent volcanic activity, around 100,000 years ago, has left vast fields of rough lava, known as malpaíses. <br><br> The highest elevation of Fuerteventura is Pico de la Zarza, at an altitude of 807 meters, located in the Jandía Peninsula, in the southern part of the island. To the northeast, just under 2 km away, is a small islet, Lobos Island, which belongs to Fuerteventura and covers an area of 4.58 km².",
	"text-5" => "The beaches are undoubtedly the main attraction of Fuerteventura. From north to south, its kilometres of white sand beaches and turquoise waters make them enchanting. More frequented, more secluded, more wild... the island has beaches for all tastes.",
	"text-6" => "The Corralejo Natural Park, located in the north of Fuerteventura, is one of the most visited places on the island. Additionally, it is home to some of the best beaches with fine white sand and emerald green waters, stretching over approximately eight kilometres. <br><br> In this area, you can find beaches such as Playa del Burro or Playa del Bajo Negro, which offer all kinds of services and amenities due to the nearby hotels; or Playa del Médano, which is perfect for windsurfing or kitesurfing, thanks to the wind currents generated in this area.",
	"text-7" => "With stunning views of the Tostón Lighthouse, the beaches of El Cotillo are a must-visit. Playa de La Concha is the most well-known beach in this area, with a vast stretch of white sand and several reefs that protect it, making it a true wonder for diving. <br><br> Also worth mentioning is El Caletón, which features various coves with white sand, and depending on the tide, the black volcanic rocks are exposed, creating a striking contrast and giving the area its unique beauty.",
	"text-8" => "Jandía has nothing to envy the Caribbean. Its fine white sand and the intense blue of its waters make it a true paradise. Among them, Playa del Matorral stands out, located in the town of Morro Jable, one of the most touristy areas of Fuerteventura. It is a 4-kilometre beach surrounded by hotels and shops, which bring great life to its avenue. <br><br> Playa de Sotavento is well known for its scene filled with kites from windsurfing enthusiasts and the sails of those practicing kitesurfing in its crystal-clear waters.",
	"text-9" => "Without a doubt, it is one of the symbols of Fuerteventura due to the spectacular nature of its landscape and the length of its beach, which stretches for no less than 12 kilometers. With the Jandía mountain range behind it, it is a pristine space that leaves an impression on everyone who passes through it.",
	"title" => "Líneas Romero Timetables. Travel with Líneas Romero in the fastest and most comfortable way.",
	"title-1" => "FUERTEVENTURA",
	"title-10" => "Lobos Island",
	"title-11" => "Hidden gems in Fuerteventura
",
	"title-12" => "Barranco de Las Peñitas and Barranco de Los Enamorados",
	"title-13" => "Esquinzo",
	"title-2" => "A sea of dunes to discover in Fuerteventura",
	"title-3" => "The origin of Fuerteventura",
	"title-4" => "Geology of the island",
	"title-5" => "The paradise beaches of Fuerteventura",
	"title-6" => "Corralejo",
	"title-7" => "El Cotillo",
	"title-8" => "Jandía Beaches",
	"title-9" => "Cofete Beaches",
];