phrase:
  access_token: 47489af89b3b5c0ba8a18df4196ecc1b039d5d15e73aae847eae7e46ebf14a30
  project_id: dca660bf649a06739d040ffce94c94d3
  file_format: laravel
  push:
    sources:

    # Spanish
    - file: ./api/lang/es/*.php
      params:
        locale_id: es
        tags: "Main files"
    - file: ./api/lang/es/emails/bookings/*.php
      params:
        locale_id: es
        tags: "Emails"
    - file: ./api/lang/es/excursions/*.php
      params:
        locale_id: es
        tags: "Excursions"
    - file: ./api/lang/es/extras/*.php
      params:
        locale_id: es
        tags: "Extras"
    - file: ./api/lang/es/pdfs/*.php
      params:
        locale_id: es
        tags: "PDFs"

    - file: ./web/lang/es/*.php
      params:
        locale_id: es
        tags: "Main files"
    - file: ./web/lang/es/destinations/*.php
      params:
        locale_id: es
        tags: "Destinations"
    - file: ./web/lang/es/errors/*.php
      params:
        locale_id: es
        tags: "Errors"
    - file: ./web/lang/es/includes/*.php
      params:
        locale_id: es
        tags: "Includes"
    - file: ./web/lang/es/schedules/*.php
      params:
        locale_id: es
        tags: "Schedules"

  pull:
    targets:

    # German
    - file: ./web/lang/fr/destinations/fuerteventura.php
      params:
        file_format: laravel
        locale_id: fr
        tags: "Destinations"
    - file: ./web/lang/fr/destinations/lanzarote.php
      params:
        file_format: laravel
        locale_id: fr
        tags: "Destinations"
    - file: ./web/lang/fr/destinations/lagraciosa.php
      params:
        file_format: laravel
        locale_id: fr
        tags: "Destinations"
    - file: ./web/lang/fr/destinations/main.php
      params:
        file_format: laravel
        locale_id: fr
        tags: "Destinations"
