<?php
return [
	"description" => "Ferry a Líneas Romero ist ein Familienunternehmen, das Fährfahrten und Ausflüge auf Lanzarote, Fuerteventura und La Graciosa anbietet. Lerne unsere Geschichte kennen.",
	"future_description" => "Die Geschwister Romero sind auf La Graciosa aufgewachsen und lieben ihre Heimat, die wilde Landschaft und den Duft des Meeres. Deshalb sind sie sich der Bedeutung des Umweltschutzes sehr bewusst und achten mit größtem Respekt auf ihre Insel und die Natur. So erfüllt Líneas Romero alle Umweltvorschriften äußerst gewissenhaft und setzt sich aktiv für einen nachhaltigen Tourismus ein. Heute betreibt Líneas Romero einen regelmäßigen Fährdienst zwischen den Inseln Fuerteventura, Lanzarote und La Graciosa. <br><br> Darüber hinaus bietet das Unternehmen einzigartige Ausflüge und touristische Erlebnisse an – darunter Segelkatamaran-Touren, um die Inseln zu entdecken und verschiedene Wassersportaktivitäten zu genießen. Ebenfalls zum Angebot gehört ein Waterbus-Service, der die bequemste Verbindung zwischen Puerto Calero und Puerto del Carmen (Lanzarote) darstellt. Líneas Romero setzt konsequent auf Innovation, entwickelt sich stetig weiter und bietet neue Dienstleistungen an, um den Bedürfnissen der Fahrgäste gerecht zu werden. Zudem wird die Flotte regelmäßig erneuert – mit schnelleren, moderneren Schiffen, ausgestattet mit neuester Technologie.",
	"future_title" => "ZUKUNFT",
	"heading" => "LERNE UNS KENNEN",
	"heading_subtitle" => "90 Jahre Verbindung von Inseln mit Engagement",
	"history_description" => "Alles begann, als Jorge M. Toledo Líneas Romero gründete und damit das erste Schifffahrtsunternehmen wurde, das den Postdienst zwischen La Graciosa und Lanzarote übernahm. Zu Beginn verfügte das Unternehmen lediglich über ein einfaches Ruderboot, mit dem die Post zwischen diesen beiden wunderschönen Atlantikinseln transportiert wurde. Ein Boot, das ausschließlich dem Postdienst gewidmet war und später von Jorge M. Toledos Tochter, Juana González Toledo, übernommen wurde. Sie heiratete schließlich Juan Romero. <br><br> Im Jahr 1970 übernahm Juan Romero die Leitung des Unternehmens und erweiterte das Dienstleistungsangebot. Juan führte Líneas Romero bis 1985, als das Geschäft an seine vier Kinder Luis, Juan Jorge, Federico und Rosa Romero überging, die das Unternehmen noch heute leiten. Die Familie Romero lebt nach wie vor auf La Graciosa und obwohl ihr Unternehmen stetig gewachsen ist, sind ihre Werte bis heute unverändert geblieben. Sie lieben ihre Arbeit und ihre Insel über alles – eine Leidenschaft, die ihnen eine erfolgreiche Unternehmensgeschichte beschert hat.",
	"history_title" => "GESCHICHTE",
	"keywords" => "Líneas Romero Geschichte Federico Romero",
	"section_description" => "Tradition und Innovation sind die beiden Hauptmerkmale von Líneas Romero. Ein Familienunternehmen, das sich der Schifffahrt verschrieben hat und seit 1930 die östlichsten Inseln der Kanarischen Inseln verbindet.",
	"section_title" => "ENTDECKE DIE GESCHICHTE VON LÍNEAS ROMERO",
	"title" => "Fahrpläne Líneas Romero. Reise mit Líneas Romero auf die schnellste und bequemste Weise",
];