<?php
return [
	"description" => "Ferry a Líneas Romero est une entreprise familiale qui propose des voyages en ferry et des excursions à Lanzarote, Fuerteventura et La Graciosa. Découvrez notre histoire.",
	"future_description" => "Les frères Romero ont grandi à La Graciosa et sont passionnés par leur terre, son paysage sauvage et son parfum de mer. C'est pourquoi ils sont conscients de l'importance de protéger l'île et respectent au maximum son environnement et sa nature. Ainsi, Líneas Romero se conforme méticuleusement aux réglementations environnementales et est une entreprise qui promeut un tourisme durable. À ce jour, Líneas Romero propose un service régulier de lignes maritimes entre les îles de Fuerteventura, Lanzarote et La Graciosa. <br><br> De plus, l'entreprise propose des excursions et des expériences touristiques uniques, comme des voyages en catamaran à voile pour découvrir les îles et profiter de diverses activités aquatiques. Elle dispose également d'un service de Waterbus, qui est le moyen le plus confortable pour voyager entre Puerto Calero et Puerto del Carmen (Lanzarote). Chez Líneas Romero, l'innovation est un véritable pari ; ils se réinventent constamment et proposent de nouveaux services pour répondre aux besoins des utilisateurs. De plus, ils renouvellent régulièrement leur flotte pour disposer de navires plus rapides, modernes et dotés des dernières technologies.",
	"future_title" => "AVENIR",
	"heading" => "NOUS CONNAÎTRE",
	"heading_subtitle" => "Depuis 90 ans, nous nous engageons à relier des îles",
	"history_description" => "Tout a commencé lorsque Jorge M. Toledo a fondé Líneas Romero, devenant ainsi la première entreprise maritime de courrier postal reliant La Graciosa et Lanzarote. À ses débuts, elle disposait d'un simple bateau à rames qui transportait le courrier entre ces deux magnifiques îles de l'Atlantique. Un navire dédié au service postal, qui a été hérité par la fille de Jorge M. Toledo, Juana González Toledo, qui a épousé par la suite Juan Romero. <br><br> C'est en 1970 que Juan Romero a pris la direction de l'entreprise, élargissant ainsi ses services. Juan a dirigé Líneas Romero jusqu'en 1985, moment où ses quatre enfants ont hérité de l'entreprise : Luis, Juan Jorge, Federico et Rosa Romero, qui sont actuellement à la tête de l'entreprise. La famille Romero vit toujours à La Graciosa et, bien que leur entreprise n'ait cessé de croître, leurs valeurs demeurent intactes. Ils aiment leur travail et leur île par-dessus tout, et leur passion les a conduits à une trajectoire pleine de succès.",
	"history_title" => "HISTOIRE",
	"keywords" => "Líneas Romero histoire Federico Romero
",
	"section_description" => "La tradition et l'innovation sont les deux principaux piliers de l'identité de Líneas Romero. Nous sommes une entreprise familiale dédiée au secteur de la navigation qui relit les îles les plus orientales des Canaries depuis 1930.",
	"section_title" => "DÉCOUVREZ L'HISTOIRE DE LÍNEAS ROMERO",
];