<?php

return [
    "title"       => "Condiciones legales generales y reglamento de viajeros | Líneas Romero",
    "description" => "Consulta el aviso legal, las condiciones generales y la política de privacidad de Líneas Romero.",
    "keywords"    => "aviso legal lineas romero",

    'heading' => 'Aviso legal',
    'intro' => 'Le agradecemos que hayas decidido visitarnos. Queremos que su experiencia en nuestra Web sea lo mejor posible.',
    'access_declaration' => 'Para acceder a nuestros servicios, declara que es <b>mayor de edad</b> y que tiene la capacidad legal suficiente para usar nuestros servicios, de acuerdo con su ley nacional. El acceso y la navegación en el sitio web, o el uso de los servicios de éste, implican la aceptación expresa e íntegra de todas y cada una de las presentes Condiciones Generales, incluidas tanto las Condiciones Particulares fijadas para ciertas promociones, así como de las Políticas de Privacidad y de las Cookies, relacionadas con la normativa vigente en la materia de Protección de Datos Personales. Por favor, le recomendamos que las lea con atención para saber qué tipo de datos se recogen a través de nuestra Web, con qué finalidades y qué derechos relacionados con ello le conciernen.',
    'section_1_title' => '1.- Información Legal.',
    'section_1_content' => 'En cumplimiento de la Ley 34/2002, de 11 de julio, de Servicios de la Sociedad de la Información y del Comercio Electrónico, los datos identificativos del titular del Portal Web son: <br> <br>
                            LINEAS ROMERO, S.L.  <br>
                            Avda. Virgen del Mar, nº119, La Graciosa, 35540, Lanzarote  <br> <br>
                            Datos de inscripción: Inscrita en el Registro Mercantil de Arrecife, tomo 4, folio 193, sección 8ª, hoja IL-182 e inscripción 2ª.  <br> <br>
                            Para cualquier duda o consulta, puede ponerse en contacto con nosotros a través del Telf:928842085 o e-mail: info@lineasromero.com  <br> <br>
                            El acceso a la Web supone la aceptación expresa del Usuario a las presentes Condiciones Generales de Uso, que podrán ser modificadas total o parcialmente o sustituidas por otras, por su titular y en cualquier momento sin previo aviso. Le recomendamos que acceda a las presentes condiciones de vez en cuando para comprobar sus posibles modificaciones, que se publicarán en el mismo apartado.',
    'section_2_title' => '2.- Condiciones Generales de Uso.',
    'section_2_content_1' => 'Las siguientes Condiciones Generales regulan el uso y acceso al portal Web, cuya finalidad es establecer pautas de buen uso y comportamiento de ésta. LINEAS ROMERO, S.L., pone a disposición de los usuarios información sobre el uso, los servicios y los contenidos que se alojan en la Web. A través ésta, el Usuario tiene acceso a información sobre productos y servicios específicos, herramientas y aplicaciones.',
    'section_2_content_2' => 'Los datos e informaciones sobre productos o servicios, precios y características u otros datos relevantes ofrecidos a través de la página web son realizados, proporcionados y actualizados por Proveedores y terceras empresas. LINEAS ROMERO, S.L. no es, en ningún caso, responsable de dichos datos e informaciones ni asume ninguna obligación sobre los mismos.',
    'section_2_content_3' => 'El Usuario se compromete a hacer un uso adecuado de los contenidos, servicios, aplicaciones y herramientas que están accesibles, con sujeción a la Ley y a las presentes Condiciones Generales de Uso y, en su caso a las Condiciones Particulares que puedan establecerse para el acceso a determinados servicios y aplicaciones, respetando en todo momento a los demás Usuarios de ésta.',
    'section_2_content_4' => 'En caso de incumplimiento total y/o parcial por el Usuario de las presentes condiciones Generales de Uso, LINEAS ROMERO, S.L. se reserva el derecho de denegar el acceso a la Web, sin necesidad de previo aviso al Usuario.',
    'section_3_title' => '3.- Obligaciones Generales del Usuario.',
    'section_3_intro' => 'El Usuario, al aceptar las presentes condiciones Generales de Uso, se obliga expresamente',
    'section_3_item_1' => 'No realizar ninguna acción destinada perjudicar, bloquear, dañar, inutilizar, sobrecargar, de forma temporal o definitiva, las funcionalidades, herramientas, contenidos y/o la infraestructura de la página web, de manera que impida su normal utilización.',
    'section_3_item_2' => 'Custodiar y mantener la confidencialidad de las claves de acceso asociadas a su nombre de Usuario, siendo responsable de la utilización de dichas claves de acceso personales e intransferibles por parte de terceros.',
    'section_3_item_3' => 'No introducir ni realizar contenidos injuriosos o calumniosos, tanto de otros Usuarios como de terceras empresas ajenas a LINEAS ROMERO, S.L.',
    'section_3_item_4' => 'No utilizar cualquiera de los materiales e informaciones contenidos en este Sitio Web con fines ilícitos y/o expresamente prohibidos en las presentes Condiciones Generales de Uso, así como a las condiciones particulares que, en su caso, se establezcan para determinadas aplicaciones y/o utilidades y que resulten contrarios a los derechos e intereses de LINEAS ROMERO, S.L., sus usuarios y/o terceros.',
    'section_3_item_5' => 'No ofertar ni distribuir productos y servicios, ni realizar publicidad o comunicaciones comerciales no solicitadas a otros Usuarios y visitantes de LINEAS ROMERO, S.L.',
    'section_3_conclusion' => 'El Usuario responderá de los todos los daños y perjuicios de toda naturaleza que LINEAS ROMERO, S.L. o cualquier tercero pueda sufrir como consecuencia del incumplimiento de cualesquiera de las obligaciones a las que queda sometido por virtud de estas “Condiciones Generales de Uso” o de la ley en relación con el acceso y/o utilización de la página.',
    'section_4_title' => '4.- Propiedad Intelectual e Industrial.',
    'section_4_content_1' => 'El sitio web, las páginas que comprende y la información o elementos contenidos en las mismas (incluyendo textos, documentos, fotografías, dibujos, representaciones gráficas, de los que es titular o de los que sean titulares terceros que autorizan al propietario a su utilización,entre otros), así como logotipos, marcas, nombres comerciales u otros signos distintivos, se encuentran protegidos por derechos de propiedad intelectual y/o industrial, de los que LINEAS ROMERO, S.L. es titular o ostenta autorización para su utilización y comunicación pública de los legítimos titulares de las mismas.',
    'section_4_content_2' => 'El Usuario se obliga a usar los contenidos de forma diligente y correcta, de acuerdo a la ley, la moral y el orden público. LINEAS ROMERO, S.L. autoriza al Usuario para visualizar la información que se contiene en este sitio web, así como para efectuar reproducciones privadas (simple actividad de descarga y almacenamiento en sus sistemas informáticos), siempre y cuando los elementos sean destinados únicamente al uso personal. En ningún caso, ello significará una autorización o licencia sobre los derechos de propiedad de LINEAS ROMERO, S.L. o de los legítimos titulares de las mismas.',
    'section_4_content_3' => 'El Usuario no está autorizado para proceder a la distribución, modificación, cesión o comunicación pública de la información contenida en esta Web en cualquier forma y cualquiera que sea su finalidad.',
    'section_5_title' => '5.- Enlaces.',
    'section_5_content_1' => 'Las conexiones y enlaces a sitios o páginas Web de terceros se han establecido únicamente como una utilidad para el Usuario. LINEAS ROMERO, S.L. no es, en ningún caso, responsable de las mismas o de su contenido.',
    'section_5_content_2' => 'LINEAS ROMERO, S.L. no asume ninguna responsabilidad derivada de la existencia de enlaces entre los contenidos de este sitio y contenidos situados fuera del mismo o de cualquier otra mención de contenidos externos a este sitio. Tales enlaces o menciones tienen una finalidad exclusivamente informativa y, en ningún caso, implican el apoyo, aprobación, comercialización o relación alguna entre LINEAS ROMERO, S.L. y las personas o entidades autoras y/o gestoras de tales contenidos o titulares de los sitios donde se encuentren.',
    'section_5_content_3' => 'Para realizar enlaces con la página Web será necesaria la autorización expresa y por escrito de los titulares del portal.',
    'section_6_title' => '6.- Responsabilidad.',
    'section_6_intro' => 'LINEAS ROMERO, S.L. no garantiza el acceso continuado, ni la correcta visualización, descarga o utilidad de los elementos e información contenidos en las páginas del portal que pueden verse impedidos, dificultados o interrumpidos por factores o circunstancias fuera de su control o ajenas a su voluntad, ni de aquellos que sean producidos por la existencia de virus informáticos en Internet.',
    'section_6_content_1' => 'LINEAS ROMERO, S.L. no asume responsabilidad alguna por daños, perjuicios, pérdidas, reclamaciones o gastos, producidos por:',
    'section_6_item_1' => 'Interferencias, interrupciones, fallos, omisiones, retrasos, bloqueos o desconexiones, motivadas por errores en las líneas y redes de telecomunicaciones o por cualquier otra causa ajena al control de LINEAS ROMERO, S.L..',
    'section_6_item_2' => 'Intromisiones ilegítimas mediante el uso de programas malignos de cualquier tipo y a través de cualquier medio de comunicación, tales como virus informáticos o cualesquiera otros',
    'section_6_item_3' => 'Uso indebido o inadecuado de la página web de LINEAS ROMERO, S.L.',
    'section_6_item_4' => 'Errores de seguridad o navegación producidos por un mal funcionamiento del navegador o por el uso de versiones no actualizadas.',
    'section_6_conclusion' => 'LINEAS ROMERO, S.L. no es responsable ni en ningún caso responderá frente a los usuarios y a terceros sobre actos de cualquier tercero ajeno a LINEAS ROMERO, S.L. que conlleve o pueda suponer la realización de actos de competencia desleal y publicidad ilícita o la infracción de los derechos de propiedad intelectual e industrial, de los secretos empresariales, de compromisos contractuales de cualquier clase, de los derechos al honor, a la intimidad personal y familiar y a la imagen, de los derechos de propiedad y de toda otra naturaleza pertenecientes a un tercero por razón de la transmisión, difusión, almacenamiento, puesta a disposición, recepción, obtención o acceso a los contenidos.',
    'section_7_title' => '7.- Protección de Datos de Carácter Personal.',
    'section_7_content' => 'Toda la política de tratamiento de datos personales la encontrarás en la Política de Privacidad, que forma parte integrante de estas Condiciones Generales pero que, por simplicidad, hemos puesto en un documento aparte: Política de Privacidad.',
    'section_8_title' => '8.- Legislación.',
    'section_8_content_1' => 'El presente Aviso Legal y sus términos y condiciones se regirán e interpretarán de acuerdo con la Legislación Española. El usuario, por el solo hecho de acceder a la página web u obtener la condición de usuario registrado otorga, de forma irrevocable, su consentimiento a que los Tribunales competentes por defecto puedan conocer de cualquier acción judicial derivada de o relacionada con las presentes condiciones, o con su uso de este Sitio o la navegación realizada por el mismo.',
    'section_8_content_2' => 'Si alguna cláusula o apartado de las presentes Condiciones Generales, que no sea de naturaleza esencial para la existencia de éste, es declarada nula o inaplicable, la validez de las restantes cláusulas no se verá afectada.',
];