<?php

return [
    'title' => 'Fuerteventura | Líneas Romero',
    'description' => 'Explora la isla mas antigua de las Canarias',
    'keywords' => 'islas, canarias, lanzarote, la graciosa, fuerteventura',

    'heading-text' => 'EXPLORA LA ISLA MÁS <br> ANTIGUA DE LAS CANARIAS',
    'title-1' => 'FUERTEVENTURA',
    'text-1' => 'Si hay una isla del Archipiélago Canario que no tenga nada que envidiar al Caribe, esa es Fuerteventura. Sus playas de arena dorada y sus agua esmeralda conquistan a todo aquel que llega hasta ella. Con Líneas Romero puedes viajar a Fuerteventura desde Lanzarote, en nuestro fast ferry de tan sólo 30 minutos de duración. ¿Quieres saber todo lo que te espera en esta maravillosa isla? No te pierdas su historia, sus playas y los mejores rincones escondidos de Fuerteventura.',
    'title-2' => 'Un mar de dunas que descubrir en Fuerteventura',
    'text-2' => 'Fuerteventura es una isla única y cautivadora, que no deja indiferente a nadie. Es la isla Canarias más próxima a África y la segunda más extensa, después de Tenerife; con una superficie de 1.659 km² y 150 kilómetros de playas bañadas por el océano Atlántico. Su belleza está protegida; siendo un territorio declarado Reserva de la Biosfera y Reserva Starlight por la Unesco. Si quieres descubrirla, en Líneas Romero contamos con un servicio regular de ferry, que en tan sólo en media hora conecta Lanzarote y Fuerteventura. <br><br> La isla cuenta con un clima de ensueño, con más de 300 días de sol al año y un nivel de precipitaciones excepcionalmente bajo. El clima de Fuerteventura es árido, con zonas pertenecientes al clima desértico y subtropical árido. Además, las condiciones de viento y olas la hacen perfecta para los amantes de deportes como el surf, windsurf y kitesurf. <br><br> Sin duda, es una joya desértica pero con kilómetros de playas paradisíacas de arena blanca o dorada y aguas turquesas que enamoran a todo aquel que las visita.',
    'title-3' => 'El origen de Fuerteventura',
    'text-3' => 'El origen de Fuerteventura se estima en el año 1.000 antes de Cristo, con la llegada de los "majos", primeros pueblos que se establecieron en la isla y que se dedicaban a la agricultura, la ganadería y la pesca. Su denominación proviene del término guanche "majo", que significaba "calzado rústico". <br><br> El nombre de la isla ha ido cambiando a lo largo del tiempo. En ese período de llegada de los "majos" se conocía como Herbania, estando este territorio dividido en dos reinos: Maxorata, al norte; y Jandía, al sur. Durante la ocupación de los romanos, se le llamó Planaria, por la geografía plana que tiene la isla; y Capraria, por la gran cantidad de cabras que habitaban este espacio. <br><br> Fue en 1402 cuando Jean Bethencourt y Gadifer de la Salle comenzaron a llevar a cabo las expediciones a Fuerteventura. No fue hasta 1405 cuando el territorio pasó a ser parte del reino de Castilla. Posteriormente los ataques de bárbaros y piratas se convirtieron en algo habitual en la isla.',
    'title-4' => 'Geología de la isla',
    'text-4' => 'Desde el punto de vista geológico, es la isla más antigua de las Canarias; formándose hace millones de años. Hoy, goza de un relieve suave como consecuencia de la erosión, aunque la actividad volcánica reciente, de hace aproximadamente 100.000 años, ha dejado amplios campos de áspera lava, denominados malpaíses. <br><br> La elevación más alta de Fuerteventura es el Pico de la Zarza, con una altitud de 807 metros, situado en la Península de Jandía, en la zona sur de la isla. Al noreste, a poco menos de 2 km de distancia, se encuentra un pequeño islote, la isla de Lobos, perteneciente a Fuerteventura, con una superficie de 4,58 km².',
    'title-5' => 'Las playas del paraíso majorero',
    'text-5' => 'Las playas son, sin duda, el mayor reclamo de Fuerteventura. De norte a sur, sus kilómetros de playa de arena blanca y aguas turquesas las hacen encantadoras. Más frecuentadas, más escondidas, más salvajes… la isla cuenta con playas para todos los gustos.',
    'title-6' => 'Corralejo',
    'text-6' => 'El Parque Natural de las Dunas de Corralejo, al norte de Fuerteventura, es uno de los lugares más visitados de la isla. Además, en él se ubican algunas de las mejores playas de fina arena blanca y aguas verde esmeralda a lo largo de unos ocho kilómetros. <br><br> En esta zona se pueden encontrar algunas playas, como la del Burro o del Bajo Negro, con todo tipo de servicios y comodidades debido a la cercanía de hoteles en la zona; o la del Médano, que es ideal para practicar windsurf o kitesurf, gracias a las corrientes de viento que se generan en esta zona.',
    'title-7' => 'El Cotillo',
    'text-7' => 'Con unas impresionantes vistas al faro del Tostón, las playas de El Cotillo son de visita obligatoria. La Playa de La Concha es la más conocida de esta zona, con una amplia extensión de arena blanca y varios arrecifes que la protegen y hacen que bucear en ella sea una auténtica maravilla. <br><br> También destaca El Caletón, que cuenta con diferentes calas de arena color blanco y, según la marea, deja ver la negra piedra volcánica, que hace contraste y le confiere su especial belleza.',
    'title-8' => 'Playas de Jandía',
    'text-8' => 'Nada tiene que envidiar Jandía al Caribe. Y es que su fina arena blanca y el color azul intenso de sus aguas las hacen un auténtico paraíso. Entre ellas destaca la playa del Matorral, situada en la localidad de Morro Jable, uno de los núcleos más turísticos de Fuerteventura. Se trata de 4 kilómetros de playa rodeada de hoteles y comercios, que dan gran vida a su avenida. <br><br> La Playa de Sotavento es bien conocida por su estampa llena de cometas de los amantes del windsurf y de las velas de los que practican kitesurf en sus aguas cristalinas.',
    'title-9' => 'Playas de Cofete',
    'text-9' => 'Sin duda, es uno de los símbolos de Fuerteventura por lo espectacular de su paisaje y la longitud de su playa, de, ni más ni menos, que 12 kilómetros. Con un macizo montañoso a su espalda, el de Jandía, es un espacio virgen que no deja indiferente a todo el que pasa por él.',
    'title-10' => 'Isla de Lobos',
    'text-10' => 'En apenas media hora en barco puedes descubrir este magnífico enclave. Isla de Lobos cuenta con dos playas: La Concha, con vistas a las dunas de Corralejo, es una tranquila bahía que se encuentra protegida de las olas. Por otra parte, se encuentra el Puertito de Lobos, cuyo contraste entre el verde esmeralda del agua, la oscura roca volcánica y el color beige de la madera del embarcadero te enamorará.',
    'title-11' => 'Joyas escondidas en Fuerteventura',
    'text-11' => 'Si eres de los que te gusta salir de los circuitos turísticos, en Fuerteventura podrás encontrar algunos lugares escondidos que son una auténtica maravilla.',
    'title-12' => 'Barranco de Las Peñitas y Barranco de Los Enamorados',
    'text-12' => 'Los amantes del senderismo pueden encontrar en el Barranco de Las Peñitas y el de Los Enamorados el lugar ideal para disfrutar de la original orografía de Fuerteventura. <br><br> El Barranco de Las Peñitas está cerca del pueblo de Betancuria. En él discurre un camino de poco más de dos kilómetros, donde además se levanta la Ermita de la Virgen de La Peña, un peculiar edificio religioso que se encuentra integrado en la piedra del barranco. <br><br> Por su parte, el Barranco de Los Enamorados, ubicado en el municipio de la Oliva -al sur del pueblo de Lajares-, es lo más parecido al Antelope Canyon en Estados Unidos que se puede ver en Canarias. Así, se trata de un singular espacio formado por dunas fósiles excavadas por el agua.',
    'title-13' => 'Esquinzo',
    'text-13' => 'Para los que prefieren la playa, Esquinzo es uno de los enclaves más tranquilos y originales de Fuerteventura, al que acuden algunos surfistas. El acceso a esta playa se realiza o recorriendo el barranco del mismo nombre, que nace en la montaña de Tindaya; o desde El Cotillo.',
    'text-14' => 'Fuerteventura cuenta con una rica, única y peculiar fauna y flora. Es hogar de muchas especies de aves, algunas endémicas canarias y otras migratorias, que cruzan su cielo y descansan en tierras majoreras durante sus largos trayectos.

    <br><br> Respecto a su vegetación, su aspecto árido esconde una riquísima variedad de especies singulares adaptadas a las condiciones climáticas. En este sentido, destacan los extensos palmerales, que forman exuberantes oasis que parecen de película.

    <br><br> No tiene bosques, está dominada por llanuras y conos volcánicos, montañas, barrancos y soporta una gran aridez ambiental. Es por eso que los campesinos majoreros se han visto obligados a agudizar su ingenio, adaptándose a la dureza del medio y aprovechando con eficacia tanto las escasas lluvias, como los frecuentes vientos. Así, el paisaje se ha visto modificado por la huella humana, consiguiendo una armonía única en el mundo.

    <br><br> Visitar la isla, disfrutar de su paisaje y su gente, es muy fácil con Líneas Romero. Viaja en nuestros ferries desde la localidad de Playa Blanca, en Lanzarote; con destino a Corralejo, uno de los núcleos turísticos más importantes de Fuerteventura. ¡En tan sólo media hora puedes llegar a esta impresionante isla!

    <br><br> Además, con Líneas Romero también tienes la opción de reservar excursiones desde Fuerteventura hacia la isla de Lanzarote, donde podrás disfrutar de un verdadero paisaje volcánico y de visitas a puntos de interés turístico como, por ejemplo, el Parque Nacional de Timanfaya. Escápate en la mejor compañía, respira la brisa del Atlántico y vive nuevas experiencias.',
];